
CREATE TABLE pipeline_runs
(
    ID SERIAL NOT NULL PRIMARY KEY,
    RUN_DATE TIMESTAMP(6) WITHOUT TIME ZONE
);

CREATE TABLE ingestion_log
(
    ID SERIAL NOT NULL PRIMARY KEY,
    PIPELINE TEXT NOT NULL,
    RECORDS_IMPORTED BIGINT NOT NULL,
    API_URL TEXT NOT NULL,
    DATE_INGESTED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE cbp_county
(
    ID SERIAL NOT NULL PRIMARY KEY,
    ESTAB INTEGER,
    EMP BIGINT,
    PAYANN BIGINT,
    PAYQTR1 BIGINT,
    NAICS TEXT,
    GEO_ID TEXT,
    STATE TEXT,
    COUNTY TEXT
);

CREATE TABLE cbp_state
(
    ID SERIAL NOT NULL PRIMARY KEY,
    ESTAB INTEGER,
    EMP BIGINT,
    PAYANN BIGINT,
    PAYQTR1 BIGINT,
    NAICS TEXT,
    GEO_ID TEXT,
    STATE TEXT,
    COUNTY TEXT
);



