psql -a -b -U ${POSTGRES_USER} -d ${POSTGRES_DB} -c "
    CREATE USER ${METABASE_POSTGRES_USER} WITH PASSWORD '${METABASE_POSTGRES_PASSWORD}' SUPERUSER;
"

psql -a -b -U ${POSTGRES_USER} -d ${POSTGRES_DB} -c "
    CREATE DATABASE ${METABASE_POSTGRES_DB} WITH OWNER '${METABASE_POSTGRES_USER}' ENCODING = 'UTF8';
"

